### ISSUE TITLE
kubeconfig overridden when running smoke tests

### ISSUE THREAD

**Issue by hawksight** [cert-manager/makefile-modules#150]
As discussed [on slack](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1716292706438929?thread_ts=1715948647.733609&cid=CDEQJ0Q8M), I was surprised to find that my kubeconfig was now much more limited than before.

```shell
> k ctx
kind-trust-manager
> k config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:59229/
  name: kind-trust-manager
contexts:
- context:
    cluster: kind-trust-manager
    namespace: cert-manager
    user: kind-trust-manager
  name: kind-trust-manager
current-context: kind-trust-manager
kind: Config
preferences: {}
users:
- name: kind-trust-manager
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
```

Previous to this I had two other kind clusters + a GKE cluster in my kubeconfig.

It would [appear here ](https://github.com/cert-manager/trust-manager/blob/b2a6689b90b1aa0b55a67b201b676588ba44afa4/make/_shared/kind/kind.mk#L60-L63)that we are overriding at the home directory level of the user, rather than in the local directories, such as `_bin/scratch`

**Comment by hawksight** [comment]
For example, I am not missing 3 other kind clusters I previously had in my kubeconfig:

```shell
> kind get clusters
cm-1-11
cse
kind
trust-manager
```

**Comment by inteon** [comment]
fixed in https://github.com/cert-manager/makefile-modules/pull/171
